version: '2'
services:
  selfskillsapplication-app:
    image: selfskillsapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://selfskillsapplication-mysql:3306/selfskillsapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://selfskillsapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://selfskillsapplication-elasticsearch:9200
    ports:
      - 8080:8080
  selfskillsapplication-mysql:
    extends:
      file: mysql.yml
      service: selfskillsapplication-mysql
  selfskillsapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: selfskillsapplication-elasticsearch
